paths:
  input_file: input/story.txt
  output_file: output/events.json

models:
  spacy_model: en_core_web_sm
  emotion_model: bhadresh-savani/distilbert-base-uncased-emotion

  # ðŸ”½ ADD THIS
  llm_model_path: models/phi-2.Q4_K_M.gguf
  llm_context_window: 512
  llm_gpu_layers: 20

performance:
  llm_scene_stride: 4
